### ISSUE TITLE
Unclear wording for "in parallel" while running WebSocket constructor

### ISSUE THREAD

**Issue by mikkorantalainen** [whatwg/websockets#13]
The [WebSocket constructor is definited to run as final step](https://websockets.spec.whatwg.org/#dom-websocket-websocket) the following:

> 9. Run this step [in parallel](https://html.spec.whatwg.org/multipage/infrastructure.html#in-parallel):
> 
> [Establish a WebSocket connection](https://websockets.spec.whatwg.org/#concept-websocket-establish) given urlRecord, protocols, and client. [[FETCH]](https://websockets.spec.whatwg.org/#biblio-fetch)

and the "in parallel" is defined as

> To run steps in parallel means those steps are to be run, one after another, at the same time as other logic in the standard (e.g., at the same time as the [event loop](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop)).

which allows interpretation that the WebSocket constructor can start a new thread to establish the WebSocket connection that runs in parallel with JavaScript engine and JavaScript event loop without syncronization of any kind.

However, typical usage of WebSocket is like

    ws = new WebSocket("wss://...");
    ws.on("error", function (error) { ... });

so in theory the first line could run the constructor which runs in parallel thread without any syncronization and fires the "error" event *before* the second line is executed. This would obviously result to missing that error event.

I think the logic is supposed to be that either the WebSocket connection is created via JS event loop syncronization or the "error" event is fired via the JS event loop to syncronize the event handling with the JS code. However, I fail to see any requirement to do this in the wording of the related specs. I'd expect some process to include "[queue a task](https://html.spec.whatwg.org/multipage/webappapis.html#queue-a-task)" step, possibly the code that handles network error before the connection is established and event `open` is triggered (which does have the step to queue a task).

**Comment by yutakahirano** [comment]
In https://websockets.spec.whatwg.org/#feedback-from-the-protocol, we have:

> When [the WebSocket connection is closed](https://tools.ietf.org/html/rfc6455#section-7.1.4), possibly [cleanly](https://tools.ietf.org/html/rfc6455#page-41:~:text=closed-,_cleanly_.), the user agent must [queue a task](https://html.spec.whatwg.org/multipage/webappapis.html#queue-a-task) to run the following substeps:

The substeps are executed on the thread on which the constructor is called.

**Comment by mikkorantalainen** [comment]
Note that that part only deals with *closing the connection*. How about opening which is the situation where the error could happen before the `ws.on("error", ...)` can be executed?

I think there should be something similar in the steps for the constructor of WebSocket(). It currently just says that the connection can be opened in parallel without talking anything about queueing a task which I would have expected. If it said that the task to open a new socket must be queued as a task there would be no issue.

**Comment by mikkorantalainen** [comment]
As I read the current spec, it would allow opening a new socket without syncronization and if local software firewall kills the connection, it could happen (in theory) before the `ws.on("error", ...)` is executed. I understand that the `close` event cannot fire until the browser native event queue has run so listening for `close` event should always work with current spec.

**Comment by ricea** [comment]
The relevant section is under [feedback from the protocol](https://websockets.spec.whatwg.org/#feedback-from-the-protocol):

> When [the WebSocket connection is closed](https://tools.ietf.org/html/rfc6455#section-7.1.4), possibly [cleanly](https://tools.ietf.org/html/rfc6455#page-41:~:text=closed-,_cleanly_.), the user agent must [queue a task](https://html.spec.whatwg.org/multipage/webappapis.html#queue-a-task) to run the following substeps:
> 
> 1. Change the [readyState](https://websockets.spec.whatwg.org/#dom-websocket-readystate) attribute’s value to [CLOSED](https://websockets.spec.whatwg.org/#dom-websocket-closed) (3).
> 
> 2. If the user agent was required to [fail the WebSocket connection](https://tools.ietf.org/html/rfc6455#section-7.1.7), or if [the WebSocket connection was closed](https://tools.ietf.org/html/rfc6455#section-7.1.4) after being flagged as full, [fire an event](https://dom.spec.whatwg.org/#concept-event-fire) named [error](https://html.spec.whatwg.org/multipage/indices.html#event-error) at the [WebSocket](https://websockets.spec.whatwg.org/#websocket) object. [[WSP]](https://websockets.spec.whatwg.org/#biblio-wsp)

It clearly says that a task is queued to fire the error event.
