### ISSUE TITLE
WebSocket and relative URLs

### ISSUE THREAD

**Issue by devsnek** [whatwg/websockets#20]
Relative URLs are good, and most assets on the web can enjoy usage of them (images, videos, flash objects, EventSource, etc), but the WebSocket constructor does not support them.

Presumably this is due to requiring a `ws` or `wss` protocol, but I would pose that using `http` and `https` is actually fine for WebSockets, as it accurately represents the method by which they acquire a connection.

So all together:
- Allow WebSocket to use http(s) protocol URLs
- If not, still allow relative URLs by mapping the protocol instead of throwing

**Comment by ricea** [comment]
I realised that allowing HTTP(S) URLs and allowing relative URLs are almost the same thing, since you could do `new WebSocket('//example.com/foo')` to connect to an arbitrary website using a relative URL. So if we were going to do this, including support for HTTP(S) schemes would be more logical from my point of view.

I still don't think the ergonomic benefit is worth the added confusion, but if some other browser implemented it I wouldn't object.

**Comment by devsnek** [comment]
I could probably contribute to chromium but webkit and gecko are a bit outside my expertise. @ricea i assume you're responsible for area of the spec for chromium, any chance of accepting theoretical work here?

**Comment by ricea** [comment]
I think I'd wait until gecko or webkit ship something before accepting a patch to chromium.

**Comment by mkurz** [comment]
Webkit implemented this recently and upcoming Safari 17 will ship that feature:
* https://github.com/WebKit/WebKit/pull/13751
* https://bugs.webkit.org/show_bug.cgi?id=247149

would be nice if others catch up also.

**Comment by annevk** [comment]
This was fixed by #45.

**Comment by qguv** [comment]
For folks affected by the change in browser behavior, here's the status as of today (2024-03-21):

- Firefox shipped in 124.0 (released 2024-03-19)
- Safari shipped this in 17 a.k.a. 19616.1.27 (released 2023-09-18)
- Chromium PR appears complete but not yet shipped in any channel:
  - ticket: https://issues.chromium.org/issues/40244242
  - review: https://chromium-review.googlesource.com/c/chromium/src/+/5060558
    - appears to be blocked awaiting an admin task (creating an entry in the platform roadmap)
    - probably no sooner than 125, which won't hit stable until 2024-05-08

The previously-mentioned https://github.com/whatwg/websockets/pull/45 has relevant links to track the implementations.

**Comment by ricea** [comment]
This is shipping in Chromium 125: https://chromestatus.com/feature/5848709993857024
