### ISSUE TITLE
Use current settings object instead of relevant settings object

### ISSUE THREAD

**Issue by zcorpan** [whatwg/websockets#46]
https://websockets.spec.whatwg.org/#dom-websocket-websocket says

> Let *client* be [this](https://webidl.spec.whatwg.org/#this)'s [relevant settings object](https://html.spec.whatwg.org/multipage/webappapis.html#relevant-settings-object).

*client*  is used for base URL for parsing relative URLs. This was introduced in https://github.com/whatwg/websockets/pull/45

I think "relevant" should be "current". See https://github.com/web-platform-tests/wpt/pull/39978#issuecomment-1548543999

> WebSocket spec says to use the relevant settings object, but going by the example in https://html.spec.whatwg.org/multipage/webappapis.html#realms-settings-objects-global-objects there's no way to test for the relevant settings object for a constructor (vs a method), since you can't use `.call()` with a constructor.
>
> I used `current` instead, like [Workers](https://html.spec.whatwg.org/multipage/workers.html#dom-worker), but this needs a spec change.

**Comment by domenic** [comment]
Inside constructors, "this's relevant settings object" === "current settings object", because of how "this" is constructed. So both are correct.

**Comment by domenic** [comment]
I'm not sure we need to add that to every spec that uses constructors, but maybe we could add it around https://html.spec.whatwg.org/#concept-relevant-everything ?

**Comment by zcorpan** [comment]
Yeah, good point. I'll open an issue for html.
